apiVersion: v1
kind: Service
metadata:
  name: servico-aplicacao
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector: # Meu objeto Sevice vai selecionar todos os pods que tem o nome especificado abaixo
    name: aplicacao-pod # esse nome tem que ser o mesmo delcarado em: metadata > labels > name no objeto pod